name: ROS2 CI

on: [push, pull_request]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  ros_gz_ci:
    name: ros_gz CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-image: "ubuntu:24.04"
            gz-version: "ionic"
            ros-distro: "rolling"
    container:
      image: ${{ matrix.docker-image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: .github/workflows/build-and-test.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker-image }}
          GZ_VERSION: ${{ matrix.gz-version  }}
          ROS_DISTRO: ${{ matrix.ros-distro }}
